### ISSUE TITLE
JSON Model is directly added in framework

### ISSUE THREAD

**Issue by iamabhiee** [citruspay/citruspay-ios-sdk#1]
Hi

JSONModel is directly added in framework causing error while using with project with jsonmodel as dependency, can you remove it from framework and add as dependency in podspec?

**Comment by muditjaju** [comment]
Trying to integrate the sdk using CocoaPods and while the JSONModel pod gets installed I keep getting the error that "JSONModel.h" file not found

**Comment by mukesh122** [comment]
resolved

**Comment by alokvnair** [comment]
Issue is still not resolved. I am getting the same error on integrating v3.6.2 via CocoaPods. Please fix it ASAP.

**Comment by sourabh-verma-citruspay** [comment]
Hi Alok. Please check and follow up my comments @ https://github.com/citruspay/citruspay-ios-sdk/issues/6
