### ISSUE TITLE
Server threw an error code 500

### ISSUE THREAD

**Issue by vinod1988** [citruspay/citruspay-ios-sdk#10]
Citrus login and every thing is working as expected. Now i am getting 500 server error on login.
Please resolve the issue as soon as possible. Let me know  why this happen.

**Comment by Pratima-Gadekar** [comment]
could you please share SDK logs. and steps followed when you get this issue?

**Comment by Pratima-Gadekar** [comment]
Issue resolved , suggested usage of correct API.
