### ISSUE TITLE
+[JSONKeyMapper mapperForSnakeCase]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by palsavita** [citruspay/citruspay-ios-sdk#13]
On running the demo project i am getting error as - 
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[JSONKeyMapper mapperForSnakeCase]: unrecognized selector sent to class

Does anyone knows the solution?

**Comment by swatisoni29** [comment]
[JSONModel.zip](https://github.com/citruspay/citruspay-ios-sdk/files/603570/JSONModel.zip)
Please replace the JSON Model folder with the shared one which will update the references.
