### ISSUE TITLE
SDK not compiling in swift 3.0.2

### ISSUE THREAD

**Issue by ssauravv22** [citruspay/citruspay-ios-sdk#14]
Unable to compile in swift 3.0.2, 
"Module compiled with Swift 3.0 cannot be imported in Swift 3.0.2"
I think the problem is with pre-built binaries.

**Comment by krishnans** [comment]
i think the problem is with the CitrusGraphics.framework with is built using swift 3.0.  I am having the same issue.

**Comment by ssauravv22** [comment]
Yes, the problem is with CitrusGraphics module. I am able to compile other frameworks.
By any chance did you find a solution to include it in latest Swift version?

**Comment by krishnans** [comment]
as of now i am using old version "4.0.2".  It Compiles without any issue

**Comment by ssauravv22** [comment]
Thanks Mate!

**Comment by mukesh122** [comment]
Guys, thanks for the comment. This issues has been take up already & you will be get fixed into coming release.
Thanks.

**Comment by mukesh122** [comment]
FYI @ssauravv22  @krishnans  - This issues has been fixed into latest CitrusGraphics SDK Version 1.1

**Comment by ssauravv22** [comment]
@mukesh122 
We are facing the same issue in CitrusPay.framework while archiving the app.
