### ISSUE TITLE
Error compiling code with CitrusSDK in Xcode 8.3

### ISSUE THREAD

**Issue by SurajSundar** [citruspay/citruspay-ios-sdk#16]
@mukesh122  I'm getting error while compiling my code with Citrus SDK in Xcode 8.3. Seems like you have to recompile the framework in Xcode 8.3. Please find the error below.
**module compiled with Swift 3.0.2 cannot be imported in Swift 3.1: /Pods/CitrusGraphics/Framework/graphics-sdk/CitrusGraphics.framework/Modules/CitrusGraphics.swiftmodule/x86_64.swiftmodule**
Please let me know the ETA for this

**Comment by mukesh122** [comment]
For further more support contact to concern team - developer.support@citruspay.com

**Comment by mukesh122** [comment]
@SurajSundar  We have released SDK for this support, kindly refer latest release.

**Comment by SurajSundar** [comment]
@mukesh122  Thank you. Issue is fixed now

**Comment by maheshlantech** [comment]
<unknown>:0: error: module compiled with Swift 3.1 cannot be imported in Swift 3.2.3: /Users/maheshkumar/Documents/Mac Data/SanyogTravel/Pods/CitrusGraphics/Framework/graphics-sdk/CitrusGraphics.framework/Modules/CitrusGraphics.swiftmodule/x86_64.swiftmodule
