### ISSUE TITLE
Swift 4 support for CitrusGraphic SDK.

### ISSUE THREAD

**Issue by SurajSundar** [citruspay/citruspay-ios-sdk#23]
@vipin04 
We are not able to use the latest version of Citrus SDK in our project as the CitrusGraphics SDK is not updated to Swift 4. Do you have an ETA for this?

**Comment by Shannaro** [comment]
@vipin04 
We are also facing the same issue.

**Comment by AalokParikh** [comment]
module compiled with Swift 3.1 cannot be imported in Swift 4.0: 

Project Directory Path/Swift4.0/eCube/Pods/CitrusGraphics/Framework/graphics-sdk/CitrusGraphics.framework/Modules/CitrusGraphics.swiftmodule/x86_64.swiftmodule

Please suggest solution.

**Comment by vipin04** [comment]
We are in process of supporting Xcode9. You can expect a new CitrusGraphics version with Swift 4.0 support in next couple of days.

**Comment by vipin04** [comment]
Framework with the support of swift 4 has been released.

**Comment by maheshlantech** [comment]
error: module compiled with Swift 3.1 cannot be imported in Swift 3.2.3: /Users/maheshkumar/Documents/Mac Data/SanyogTravel/Pods/CitrusGraphics/Framework/graphics-sdk/CitrusGraphics.framework/Modules/CitrusGraphics.swiftmodule/x86_64.swiftmodule
