### ISSUE TITLE
CitrusPay.framework incompatible with swift4.0

### ISSUE THREAD

**Issue by AalokParikh** [citruspay/citruspay-ios-sdk#24]
ProjectPath/CitrusPay.framework/CitrusPay compiled with older version of Swift language (3.0) than previous files (4.0) 

file 'ProjectPath/Swift4.0/eCube/Pods/CitrusPay/Framework/core-sdk/CitrusPay.framework/CitrusPay' for architecture x86_64

**Comment by Shannaro** [comment]
Facing the same issue

**Comment by mickyarun** [comment]
Facing the same issue, any solution?

**Comment by kavitathorat** [comment]
facing the same issue, Please upgrade

**Comment by vipin04** [comment]
Please update the CitrusPay SDK to 4.1.7
https://github.com/citruspay/citruspay-ios-sdk/releases/tag/4.1.7
