### ISSUE TITLE
CitrusGraphics do not works with xcode 9.1 and Swift 4.0.2

### ISSUE THREAD

**Issue by AalokParikh** [citruspay/citruspay-ios-sdk#26]
module compiled with Swift 4.0 cannot be imported in Swift 4.0.2: /Users/dhaval.sabhaya/Desktop/Swift4.0/eCube/Pods/CitrusGraphics/Framework/graphics-sdk/CitrusGraphics.framework/Modules/CitrusGraphics.swiftmodule/x86_64.swiftmodule

**Comment by vipin04** [comment]
The support for newer versions of Swift (4.0.2 and later) is in pipeline.
Please use Xcode version 9.0 till then.
