### ISSUE TITLE
Pods/CitrusGraphics/Framework

### ISSUE THREAD

**Issue by maheshlantech** [citruspay/citruspay-ios-sdk#39]
<unknown>:0: error: module compiled with Swift 3.1 cannot be imported in Swift 3.2.3: /Users/maheshkumar/Documents/Mac Data/SanyogTravel/Pods/CitrusGraphics/Framework/graphics-sdk/CitrusGraphics.framework/Modules/CitrusGraphics.swiftmodule/x86_64.swiftmodule

**Comment by RajvinderPayU** [comment]
Which version of CitrusGraphics are you using? If it is not the latest one, update it and then try. Here is the link for latest release:
https://github.com/citruspay/citruspay-ios-sdk/releases/tag/graphics.2.1.0
