### ISSUE TITLE
full bitcode issue while generating bundle

### ISSUE THREAD

**Issue by geniusrocky** [citruspay/citruspay-ios-sdk#5]
Encountered issue when archived with bitcode.

bitcode bundle could not be generated because '/Users/sarav/Desktop/housejoy/Pods/CitrusPay/CitrusPay-Framework/CitrusPay.framework/CitrusPay(CTSProfilePrepaidRes.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

**Comment by mukesh122** [comment]
This is has been resolved, you can check with latest SDK version.

**Comment by sourabh-verma-citruspay** [comment]
@geniusrocky : Can you confirm that issue doesn't exist anymore ?
