### ISSUE TITLE
Server threw an error code 500

### ISSUE THREAD

**Issue by nileshpol18** [citruspay/citruspay-ios-sdk#7]
on requestPaymentsModes() method, I get following error:

**Error Domain=com.citrus.errorDomain Code=7007 "Server threw an error
code 500**

**Comment by vasun77** [comment]
+1

**Comment by karmn92** [comment]
+1

**Comment by Pratima-Gadekar** [comment]
@nileshpol18 Is your bill url hosted correctly on a server? And could you share your Billurl response to pratima.gadekar@citruspay.com and also ur SDK logs

**Comment by SrinivasaLadi** [comment]
@Pratima-Gadekar  i am facing same issue and sent the logs to your email. please check and do let me know what might be the problem

**Comment by Pratima-Gadekar** [comment]
@nileshpol18 @vasun77 @karmn92 @SrinivasaLadi was the issue resolved?

**Comment by chinmayabehera** [comment]
I am also facing the same error. plz help.

**Comment by kavitathorat** [comment]
facing same error, please help @Pratima-Gadekar

**Comment by maheshlantech** [comment]
[CitrusPay SDK] Version 4.1.8 : Property error Value: Error Domain=com.citrus.errorDomain Code=7007 "Server threw an error
code 403" UserInfo={NSLocalizedDescription=Server threw an error
code 403}


When i am usign production credentials in ios integration
