### ISSUE TITLE
getting this issue  [CitrusPay SDK v3.1.3] 

### ISSUE THREAD

**Issue by somsin** [citruspay/citruspay-ios-sdk#8]
[CitrusPay SDK v3.1.3] 
Error Domain=com.citrus.errorDomain Code=7007 "Server threw an error
code 500" UserInfo={NSLocalizedDescription=Server threw an error
code 500, CTSServerErrorDescription=(null description)}
 i am getting this issue

**Comment by ratanlp** [comment]
Getting same error. Can anyone from Citrus team help here.

**Comment by mukesh122** [comment]
What is scenario?

**Comment by ratanlp** [comment]
Resolved it in sandbox env. The issue was that from backend I was getting production "merchantAccessKey" instead of sandbox one.

**Comment by IshaVason** [comment]
Error Domain=com.citrus.errorDomain Code=7007 "request validation error" UserInfo={NSLocalizedDescription=request validation error, CTSServerErrorDescription=(null description)}

i am getting this issue

**Comment by IshaVason** [comment]
Can anyone from Citrus team help here.

**Comment by maheshlantech** [comment]
Property error Value: Error Domain=com.citrus.errorDomain Code=7007 "Server threw an error
code 401" UserInfo={NSLocalizedDescription=Server threw an error


when I am using  Prod Env.

**Comment by maheshlantech** [comment]
[CitrusPay SDK] Version 4.1.8 : Property headers Value: {
    Authorization = "Bearer (null)";

when I am using Prod Env. But sandbox env running properly
