### ISSUE TITLE
How to integrate Citrus Quick payment for credit card and debit card without asking user to login in IOS? 

### ISSUE THREAD

**Issue by dipmajithiya** [citruspay/citruspay-ios-sdk#9]
I am trying to integrate CitrusPay SDK to my iPhone application. How can i integrate CitrusPay Direct payment without asking user to login to citrus pay.

I want to give options to user like :

Pay using Citrus Wallet
Pay using Creditcard/Debit Card
Pay using Net banking
If user would like to pay using Citrus Wallet then i will ask user to login to citrus using their credentials. If they will go with 2nd or 3rd option like pay using Credit Card/Debit Card or net banking then they don't need to login.

I want to implement this function in my app using CitrusPay SDK. Can you point out me for the code of this?

I already have a demo of the Citrus pay and i already checked it.

https://github.com/citruspay/citruspay-ios-sdk

I downloaded the demo from the above link.

Please help me out for this.

**Comment by mukesh122** [comment]
Once the initialize the SDK, follow this guide for payment flow -
https://github.com/citruspay/citruspay-ios-sdk/wiki/3.--Integrating-CTSPaymentLayer

On Thu, Jun 2, 2016 at 11:58 AM, Dipen Majithiya <notifications@github.com>
wrote:

> I am trying to integrate CitrusPay SDK to my iPhone application. How can i
> integrate CitrusPay Direct payment without asking user to login to citrus
> pay.
>
> I want to give options to user like :
>
> Pay using Citrus Wallet
> Pay using Creditcard/Debit Card
> Pay using Net banking
> If user would like to pay using Citrus Wallet then i will ask user to
> login to citrus using their credentials. If they will go with 2nd or 3rd
> option like pay using Credit Card/Debit Card or net banking then they don't
> need to login.
>
> I want to implement this function in my app using CitrusPay SDK. Can you
> point out me for the code of this?
>
> I already have a demo of the Citrus pay and i already checked it.
>
> https://github.com/citruspay/citruspay-ios-sdk
>
> I downloaded the demo from the above link.
>
> Please help me out for this.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/citruspay/citruspay-ios-sdk/issues/9>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AISpy5MYfi4-jQ9_11l8UwHOMcQy9q-fks5qHnf9gaJpZM4IsPe->
> .
>



-- 

Thanks,

Warm Regards,

*Mukesh Patil*

Citrus Payments

www.citruspay.com
[image: cid:image001.jpg@01CCEBE7.72A3EC60]

**Comment by dipmajithiya** [comment]
Yes i already tried with the same with testing credit card data. But i am always getting TXN not authorized. "Txn cannot be authorized"

Can you please help me out? I am not asking for user to login to citrus.

**Comment by mukesh122** [comment]
Have you initialized SDK using provided valid Oauth testing keys?

**Comment by mukesh122** [comment]
For further more support contact to this team - developer.support@citruspay.com

**Comment by dipmajithiya** [comment]
Yes i have done that initialization. I already sent an email to "developer.support@citruspay.com" as well but no reply so far.

**Comment by mukesh122** [comment]
Okay, can you send queries again on this also mobiledev@citruspay.com

**Comment by dipmajithiya** [comment]
Ok let me do that.

**Comment by dipmajithiya** [comment]
I sent email to mobiledev@citruspay.com.

**Comment by maheshlantech** [comment]
**CitrusPay Complete the Transaction, Merchant Server did Not Return Data From postResponseiOS()**

when usign amount get citrys side


$value = $_GET["amount"]; //Charge amount is in INR by default  

**But proper running when amount value passing static**

**Comment by maheshlantech** [comment]
@vipin04 

CitrusPay Complete the Transaction, Merchant Server did Not Return Data From postResponseiOS()

when usign amount get citrys side

$value = $_GET["amount"]; //Charge amount is in INR by default

But proper running when amount value passing static
